SalesUI/Controllers/TicketController.cs
using Business;
using Business.Business;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models;
using SalesUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace SalesUI.Controllers
{
    public class TicketController : Controller
    {
        private readonly TicketBusiness ticketBusiness;
        private readonly BusinessClient clientBusiness;
        private readonly BusinessItem itemBusiness;
        private readonly ProductBusiness productBusiness;

        public TicketController(TicketBusiness _context, BusinessClient __context, BusinessItem context_, ProductBusiness context__)
        {
            ticketBusiness = _context;
            clientBusiness = __context;
            itemBusiness = context_;
            productBusiness = context__;
        }

        // GET: Ticket
        public ActionResult Index(string searchString)
        {
            var client = new Client();
            if (!String.IsNullOrEmpty(searchString))
            {
                client = clientBusiness.GetById(Convert.ToInt32(searchString));
            }
            if(client == null)
            {
                return ViewComponent("Error");
            }
            var clientview = new ClientViewModel(client);
            return View(clientview);
          
        }

        //Ticket/ListItem/ {id}
        public ActionResult ListItem(int id)
        {
            var client = clientBusiness.GetById(id);
            var clientview = new ClientViewModel(client);
            ViewBag.Id_Client = id;
            ViewBag.Id_products = new SelectList(productBusiness.GetAll(), "Id", "Details");
            return View();
        }

        public ActionResult AddItem(int clientid, ItemViewModel itemViewModel)
        {
            if (ModelState.IsValid)
            {
                Random rnd = new Random();
               Item item =  itemViewModel.aItem();
                item.Product = productBusiness.GetById(item.ProductId);
                item.Total = itemBusiness.CalculateTotal(item);
                item.TicketId = 3;
                ViewBag.Id_Client = clientid;
                itemBusiness.Insert(item);
            }
            return RedirectToAction("ListItem", new { id = clientid });
        }

        /* 
        // GET: Ticket/Create
        public ActionResult Create()
        {
            return View();
        }
        
        // POST: Ticket/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Ticket/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Ticket/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Ticket/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Ticket/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }*/
    }
}

SalesUI/Views/Ticket/GetClientById.cshtml
@model SalesUI.Models.ClientViewModel

@{
    ViewData["Title"] = "GetClientById";
}

<h1>GetClientById</h1>

<div>
    <h4>ClientViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Document)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Document)
        </dd>
    </dl>
</div>
<div>

</div>

SalesUI/Views/Ticket/Index.cshtml
@model SalesUI.Models.ClientViewModel
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<form asp-controller="Ticket" asp-action="Index">
    <p>
        Title: <input type="text" name="SearchString">
        <input type="submit" value="Filter" />
    </p>
</form>


<h1>GetClientById</h1>

@if (Model.Id != 0)
{


<div>
    <h4>ClientViewModel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Mail)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Mail)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Document)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Document)
        </dd>
    </dl>
</div>
<div>

</div>

@Html.ActionLink("Comenzar compra", "ListItem", "Ticket", new { id = Model.Id }, null);
}

SalesUI/Views/Ticket/ListItem.cshtml
@using Models;
@using Business.Business;

@inject BusinessItem itemBusiness

@model SalesUI.Models.ItemViewModel


@{
    ViewData["Title"] = "ListItem";
}

<h1>@ViewBag.Id_Client</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Product)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quanty)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in itemBusiness.GetAll())
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Details)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quanty)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Total)
                </td>
            </tr>
        }
    </tbody>
</table>

@using (Html.BeginForm("AddItem", "Ticket", new { clientid = @ViewBag.Id_Client }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Empleado</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.ProductId, "Product", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ProductId", ViewBag.Id_products as IEnumerable<SelectListItem>, null, htmlAttributes: new { @class = " form-control " })
            @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Quanty, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.EditorFor(model => model.Quanty, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Quanty, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-success" />
        </div>
    </div>
</div>

}

SalesUI/Views/Ticket/View.cshtml
@*@model SalesUI.Models.ItemViewModel

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<h4>ItemViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="View">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product" class="control-label"></label>
                <input asp-for="Product" class="form-control" />
                <span asp-validation-for="Product" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <input asp-for="ProductId" class="form-control" />
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TicketId" class="control-label"></label>
                <input asp-for="TicketId" class="form-control" />
                <span asp-validation-for="TicketId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quanty" class="control-label"></label>
                <input asp-for="Quanty" class="form-control" />
                <span asp-validation-for="Quanty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>*@